apiVersion : apps/v1
kind: Deployment
metadata:
  name: "transactionapi12-9988"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "transactionapi12-9988"
  template:
    metadata:
      labels:
        app: "transactionapi12-9988"
    spec:
      containers:
        - name: "transactionapi12-9988"
          image: "transactionapi1.azurecr.io/transactionapi12"
          ports:
          - containerPort: 80