on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: accountscr.azurecr.io
        username: ${{ secrets.acr_accountscr_username }}
        password: ${{ secrets.acr_accountscr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t accountscr.azurecr.io/bankingaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push accountscr.azurecr.io/bankingaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bankingaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bankingaksaa74 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bankingaksaa74`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bankingaksaa74
        container-registry-url: accountscr.azurecr.io
        container-registry-username: ${{ secrets.acr_accountscr_username }}
        container-registry-password: ${{ secrets.acr_accountscr_password }}
        secret-name: bankingaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: bankingaksaa74
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          accountscr.azurecr.io/bankingaks:${{ github.sha }}
        imagepullsecrets: |
          bankingaksdockerauth
